# Generated by Django 5.1.2 on 2024-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_book_isbn_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="0000000000000", max_length=13),
        ),
    ]
