# Generated by Django 5.1.2 on 2024-12-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returning",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
