# Generated by Django 5.1.2 on 2024-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_returning_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returning",
            name="return_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
