# Generated by Django 5.1.2 on 2024-12-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_borrowing_borrow_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
