# Generated by Django 5.1.2 on 2024-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_book_book_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="0000000000000", max_length=13, unique=True),
        ),
    ]
